services:
  db:
    image: postgres:14
    container_name: etl-postgres
    restart: always
    environment:
      POSTGRES_DB: etldb
      POSTGRES_USER: etluser
      POSTGRES_PASSWORD: etlpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "etluser", "-d", "etldb"]
      interval: 5s
      timeout: 3s
      retries: 5

  etl:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  pgdata:
